name: run_tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'
  release:
    types: [published]

jobs:
  run_tests:
    name: Build and run tests on ${{ matrix.os }} with Python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.9", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install pytest
      run: python -m pip install pytest
    
    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build/ -DBUILD_TESTS=1

    - name: Build test modules
      run: |
        cmake --build $GITHUB_WORKSPACE/build/
        ls
        ls build

    - name: Download Dependencies CLI
      run: |
        curl -L -o dependencies.zip https://github.com/lucasg/Dependencies/releases/download/1.12.0/Dependencies-v1.12.0-x64.zip
        tar -xf dependencies.zip

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run tests
      run: |
        cd build/Debug
        python -m pytest ../../tests