name: run_tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'
  release:
    types: [published]

jobs:
  run_tests:
    name: Build and run tests on ${{ matrix.os }} with Python${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        check-latest: false

    - name: Install pytest
      run: python -m pip install pytest
    
    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build/ -DBUILD_TESTS=1

    - name: Build test modules
      run: |
        cmake --build $GITHUB_WORKSPACE/build/

    - name: Run tests
      if: ${{ !startsWith(matrix.os, 'windows') }}
      run: |
        cd build/
        python -m pytest ../tests

    # TODO: Run on other Python versions on Windows (Missing/not-matching DLLs error)
    - name: Run tests
      if: ${{ startsWith(matrix.os, 'windows') && matrix.python == '3.13' }}
      run: |
        cd build/Debug
        python -m pytest ../../tests